name: mmoInfoTime
version: ${releaseVersion}.${buildNumber}
author: mmoMinecraftDev
website: http://mmo.me.uk
main: mmo.Info.mmoInfoTime
depend: [Spout,mmoCore,mmoInfo]
description: Adds {time} to the info tokens
permissions:
  mmo.info.time:
    description: Allows {world-time} to show current and max users on server.
    default: true
